baseURL = "https://www.showyourspace.net/"
languageCode = "en-us"
title = "Show Your Space"
theme = "hugo-theme-gallery"
copyright = "Â© {year} Show Your Space"

[pagination]
  pagerSize = 999999

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.vimeo]
    disabled = false
    simple = true
  [privacy.x]
    disabled = false
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = false
    simple = true
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

[params]
  defaultTheme = "dark"
  
  [params.gallery]
    downloadOriginals = true
    showExif = true

[author]
  name = "Show Your Space"
  homepage = "https://showyourspace.github.io/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"